- service_alias: MindSpore Internship
  service_introduce: ''
- service_alias: openEuler Package Build
  service_introduce: openEuler社区OBS
- service_alias: openEuler Jenkins CI
  service_introduce: openEuler镜像构建Jenkins服务
- service_alias: Kunpenghui Jenkins
  service_introduce: 鲲鹏Jenkins
- service_alias: Gitee Website
  service_introduce: ''
- service_alias: openLooKeng SMTP
  service_introduce: openLooKeng社区邮件发送服务
- service_alias: openLooKeng Jenkins
  service_introduce: openLooKeng社区Jenkins服务
- service_alias: openLookeng docs
  service_introduce: ''
- service_alias: openLooKeng Website
  service_introduce: openLooKeng社区官网
- service_alias: openLooKeng docs-bug
  service_introduce: openLooKeng社区文档捉虫服务
- service_alias: openLooKeng Search
  service_introduce: ''
- service_alias: openEuler Datastat Omapi
  service_introduce: Datastat后台服务
- service_alias: openLooKeng paste
  service_introduce: 上传代码生成分享链接
- service_alias: openLooKeng Mailweb
  service_introduce: openLooKeng社区邮件列表
- service_alias: openLooKeng Tryme
  service_introduce: openLooKeng集群部署介绍网站
- service_alias: openGauss Mailweb
  service_introduce: openGauss社区邮箱
- service_alias: openLooKeng Datastat
  service_introduce: openLooKeng社区数据展示
- service_alias: openEuler Discourse
  service_introduce: openEuler社区论坛
- service_alias: openEuler Meetings
  service_introduce: openEuler社区会议小程序
- service_alias: openEuler Moscow Mirror
  service_introduce: openEuler俄罗斯镜像下载网站
- service_alias: MindSpore Mailweb
  service_introduce: MindSpore社区邮箱列表
- service_alias: openGauss Jenkins
  service_introduce: openGauss社区jenkins服务
- service_alias: MindSpore Jenkins
  service_introduce: MindSpore社区Jenkins
- service_alias: openEuler CVE Manager
  service_introduce: openEuler社区CVE管理状态展示
- service_alias: openEuler France Mirror
  service_introduce: openEuler巴黎镜像站点
- service_alias: openEuler Search
  service_introduce: ''
- service_alias: openEuler Mailling List
  service_introduce: openEuler社区邮箱列表
- service_alias: Mindspore search
  service_introduce: ''
- service_alias: openEuler Quickissue Backend
  service_introduce: openEuler社区Issue和PR快速提交平台后台服务
- service_alias: MAJUN
  service_introduce: 代码门禁
- service_alias: Metadata Service
  service_introduce: 代码仓元数据下载
- service_alias: openEuler HongKong Mirror
  service_introduce: openEuler镜像下载网站
- service_alias: openGauss Etherpad
  service_introduce: 记事本
- service_alias: MindSpore Xihe
  service_introduce: N思大模型平台
- service_alias: openEuler Etherpad
  service_introduce: 记事本
- service_alias: MindSpore Internship New
  service_introduce: ''
- service_alias: MindSpore SMTP
  service_introduce: MindSpore社区邮件发送服务
- service_alias: MindSpore Sunmao
  service_introduce: MindSpore社区标签机器人服务
- service_alias: openEuler Bugzilla
  service_introduce: ''
- service_alias: openEuler Copr
  service_introduce: ''
- service_alias: openEuler HongKong
  service_introduce: openEuler官网
- service_alias: openEuler License Show Room
  service_introduce: 貂蝉License展示
- service_alias: openEuler SMTP
  service_introduce: openEuler社区邮件发送服务
- service_alias: openEuler Compass CI Platform
  service_introduce: 开发式测试服务平台Compass CI首页
- service_alias: openGauss Docs
  service_introduce: ''
- service_alias: openGauss Search
  service_introduce: ''
- service_alias: openGauss SMTP
  service_introduce: openGauss社区邮件发送服务
- service_alias: openLooKeng Download
  service_introduce: openLooKeng社区资源下载服务
- service_alias: paas robot
  service_introduce: Kurator项目prow机器人
- service_alias: Software Composition Analysis
  service_introduce: 风险数据看板
- service_alias: Test Domain Monitor
  service_introduce: ''
- service_alias: openEuler OmniBuildPlatform
  service_introduce: openEuler社区镜像构建下载服务
- service_alias: openEuler QA Robot
  service_introduce: openEuler社区客服机器人欧拉小智
- service_alias: openEuler Package Manage
  service_introduce: openEuler Package Management
- service_alias: openEuler QuickIssue
  service_introduce: openEuler社区Issue和PR快速提交平台前端服务
- service_alias: openEuler User Repo Mirror
  service_introduce: openEuler用户镜像站点
- service_alias: openEuler Community Certificate
  service_introduce: openEuler社区认证服务
- service_alias: openEuler Usercenter
  service_introduce: openEuler社区用户中心
- service_alias: openEuler NestOS
  service_introduce: openEuler NestOS云底座操作系统前端服务
- service_alias: openEuler MirrorManager
  service_introduce: openEuler官网
- service_alias: openEuler Reproducible Builds
  service_introduce: openEuler可重复构建
- service_alias: Community Talent Certification
  service_introduce: openEuler社区人才认证IT系统
- service_alias: Explainshell
  service_introduce: Shell命令解释服务
- service_alias: openEuler PlayGround2
  service_introduce: openEuler学习平台
- service_alias: Infra Ops
  service_introduce: 基础设施运维平台
- service_alias: openEuler-ECS-Prometheus
  service_introduce: prometheus监控服务
- service_alias: openGauss Usercenter
  service_introduce: openGauss社区用户中心
- service_alias: openGauss odd
  service_introduce: openGauss社区开发者大会人传人海报生成服务
- service_alias: openGauss HongKong Website
  service_introduce: openGauss官网
- service_alias: openGauss Blog
  service_introduce: openGauss博客
- service_alias: openGauss Meetings
  service_introduce: openGauss社区会议小程序
- service_alias: openGauss Moocstudio
  service_introduce: openGauss社区学习平台
- service_alias: openGauss Reproducible Builds
  service_introduce: openGauss可重复构建
- service_alias: MindSpore Download
  service_introduce: MindSpore资源下载
- service_alias: MindSpore Binaries
  service_introduce: MindSpore包管理
- service_alias: voting
  service_introduce: helios投票服务
- service_alias: MindSpore WWW
  service_introduce: MindSpore官网
- service_alias: MindSpore Xihe Doc
  service_introduce: N思文档
- service_alias: MindSpore Meetings
  service_introduce: MindSpore会议小程序
- service_alias: MindSpore Reproducible Builds
  service_introduce: MindSpore可重复构建
- service_alias: openEuler Moscow
  service_introduce: openEuler俄语官网
- service_alias: openEuler Beijing Mirror
  service_introduce: openEuler镜像北京下载地址
- service_alias: openEuler Document
  service_introduce: openEuler社区文档
- service_alias: Etherpad
  service_introduce: 记事本
- service_alias: MindSpore Website
  service_introduce: MindSpore官网
- service_alias: MindSpore Datastat
  service_introduce: MindSpore社区数据展示
- service_alias: openEuler PlayGround
  service_introduce: openEuler学习平台
- service_alias: Contributor License Agreement
  service_introduce: 开源社区SLA签署
- service_alias: MindSpore paste
  service_introduce: 上传代码生成分享链接
- service_alias: openEuler paste
  service_introduce: 上传代码生成分享链接
- service_alias: openGauss paste
  service_introduce: 上传代码生成分享链接
- service_alias: openGauss Datastat
  service_introduce: openGauss社区数据展示
- service_alias: Majun anti-poison
  service_introduce: Majun防投毒
- service_alias: Majun source clean
  service_introduce: Majun来源清洁
- service_alias: openEuler Copr
  service_introduce: openEuler用户仓服务

