- service_alias: MindSpore Internship
  service_introduce: ''
  url: https://internship.mindspore.cn/zh/internship/
- service_alias: openEuler Package Build
  service_introduce: openEuler社区OBS
  url: https://build.openeuler.org/
- service_alias: openEuler Jenkins CI
  service_introduce: openEuler镜像构建Jenkins服务
  url: https://openeulerjenkins.osinfra.cn/computer/
- service_alias: Kunpenghui Jenkins
  service_introduce: 鲲鹏Jenkins
  url: https://kunpengaccci.osinfra.cn/computer/
- service_alias: Gitee Website
  service_introduce: ''
  url: https://gitee.com
- service_alias: openLooKeng SMTP
  service_introduce: openLooKeng社区邮件发送服务
  url: mail.openlookeng.io
- service_alias: openLooKeng Jenkins
  service_introduce: openLooKeng社区Jenkins服务
  url: https://build.openlookeng.io/computer/
- service_alias: openLookeng docs
  service_introduce: ''
  url: https://docs.openlookeng.io
- service_alias: openLooKeng Website
  service_introduce: openLooKeng社区官网
  url: https://openlookeng.io
- service_alias: openLooKeng docs-bug
  service_introduce: openLooKeng社区文档捉虫服务
  url: https://docs-bug.openlookeng.io
- service_alias: openLooKeng Search
  service_introduce: ''
  url: https://search.openlookeng.io/docs
- service_alias: openEuler Datastat Omapi
  service_introduce: Datastat后台服务
  url: https://datastat.openeuler.org/query/all?community=openeuler
- service_alias: openLooKeng paste
  service_introduce: 上传代码生成分享链接
  url: https://paste.openlookeng.io
- service_alias: openLooKeng Mailweb
  service_introduce: openLooKeng社区邮件列表
  url: https://mailweb.openlookeng.io/postorius/lists/
- service_alias: openLooKeng Tryme
  service_introduce: openLooKeng集群部署介绍网站
  url: https://tryme.openlookeng.io
- service_alias: openGauss Mailweb
  service_introduce: openGauss社区邮箱
  url: https://mailweb.opengauss.org/postorius/lists/
- service_alias: openLooKeng Datastat
  service_introduce: openLooKeng社区数据展示
  url: https://datastat.openlookeng.io
- service_alias: openEuler Discourse
  service_introduce: openEuler社区论坛
  url: https://forum.openeuler.org/
- service_alias: openEuler Meetings
  service_introduce: openEuler社区会议小程序
  url: https://meetings.openeuler.org/groups/
- service_alias: openEuler Moscow Mirror
  service_introduce: openEuler俄罗斯镜像下载网站
  url: https://ru-repo.openeuler.org/
- service_alias: MindSpore Mailweb
  service_introduce: MindSpore社区邮箱列表
  url: https://mailweb.mindspore.cn/postorius/lists/
- service_alias: openGauss Jenkins
  service_introduce: openGauss社区jenkins服务
  url: https://jenkins.opengauss.org/computer/
- service_alias: MindSpore Jenkins
  service_introduce: MindSpore社区Jenkins
  url: https://build.mindspore.cn/computer/
- service_alias: openEuler CVE Manager
  service_introduce: openEuler社区CVE管理状态展示
  url: https://api.openeuler.org/cve-manager/v1/cve/issue
- service_alias: openEuler France Mirror
  service_introduce: openEuler巴黎镜像站点
  url: https://fr-repo.openeuler.org/
- service_alias: openEuler Search
  service_introduce: ''
  url: https://www.openeuler.org/api-search/search/docs
- service_alias: openEuler Mailling List
  service_introduce: openEuler社区邮箱列表
  url: https://mailweb.openeuler.org/postorius/lists/
- service_alias: Mindspore search
  service_introduce: ''
  url: https://www.mindspore.cn/searchdoc
- service_alias: openEuler Quickissue Backend
  service_introduce: openEuler社区Issue和PR快速提交平台后台服务
  url: https://ipb.osinfra.cn/issues/types
- service_alias: MAJUN
  service_introduce: 代码门禁
  url: https://majun.osinfra.cn
- service_alias: Metadata Service
  service_introduce: 代码仓元数据下载
  url: https://api.osinfra.cn/metadata/health
- service_alias: openEuler HongKong Mirror
  service_introduce: openEuler镜像下载网站
  url: https://repo.openeuler.org/
- service_alias: openGauss Etherpad
  service_introduce: 记事本
  url: https://etherpad.opengauss.org
- service_alias: MindSpore Xihe
  service_introduce: N思大模型平台
  url: https://xihe.mindspore.cn
- service_alias: openEuler Etherpad
  service_introduce: 记事本
  url: https://etherpad.openeuler.org/
- service_alias: MindSpore Internship New
  service_introduce: ''
  url: https://new.mindspore.cn
- service_alias: MindSpore SMTP
  service_introduce: MindSpore社区邮件发送服务
  url: mail.mindspore.cn
- service_alias: MindSpore Sunmao
  service_introduce: MindSpore社区标签机器人服务
  url: https://sunmao.mindspore.cn
- service_alias: openEuler Bugzilla
  service_introduce: ''
  url: https://bugzilla.openeuler.org/
- service_alias: openEuler Copr
  service_introduce: ''
  url: https://eur.openeuler.openatom.cn/
- service_alias: openEuler HongKong
  service_introduce: openEuler官网
  url: https://openeuler.org/zh/
- service_alias: openEuler License Show Room
  service_introduce: 貂蝉License展示
  url: https://compliance.openeuler.org/
- service_alias: openEuler SMTP
  service_introduce: openEuler社区邮件发送服务
  url: 159.138.46.20
- service_alias: openEuler Compass CI Platform
  service_introduce: 开发式测试服务平台Compass CI首页
  url: https://compass-ci.openeuler.org/
- service_alias: openGauss Docs
  service_introduce: ''
  url: https://docs.opengauss.org
- service_alias: openGauss Search
  service_introduce: ''
  url: https://opengauss.org/api-search/search/docs
- service_alias: openGauss SMTP
  service_introduce: openGauss社区邮件发送服务
  url: mail.opengauss.org
- service_alias: openLooKeng Download
  service_introduce: openLooKeng社区资源下载服务
  url: https://download.openlookeng.io
- service_alias: paas robot
  service_introduce: Kurator项目prow机器人
  url: https://paas-prow.osinfra.cn/hook
- service_alias: Software Composition Analysis
  service_introduce: 风险数据看板
  url: https://sca.osinfra.cn/
- service_alias: Test Domain Monitor
  service_introduce: ''
  url: https://xihe2.test.osinfra.cn
- service_alias: openEuler OmniBuildPlatform
  service_introduce: openEuler社区镜像构建下载服务
  url: https://omni.openeuler.sh
- service_alias: openEuler QA Robot
  service_introduce: openEuler社区客服机器人欧拉小智
  url: https://qa-robot.openeuler.org/
- service_alias: openEuler Package Manage
  service_introduce: openEuler Package Management
  url: https://pkgmanage.openeuler.org/
- service_alias: openEuler QuickIssue
  service_introduce: openEuler社区Issue和PR快速提交平台前端服务
  url: https://quickissue.openeuler.org/zh/issues/
- service_alias: openEuler User Repo Mirror
  service_introduce: openEuler用户镜像站点
  url: https://user-repo.openeuler.openatom.cn
- service_alias: openEuler Community Certificate
  service_introduce: openEuler社区认证服务
  url: https://ccs.openeuler.org/actuator/health/liveness
- service_alias: openEuler Usercenter
  service_introduce: openEuler社区用户中心
  url: https://id.openeuler.org/zh/profile
- service_alias: openEuler NestOS
  service_introduce: openEuler NestOS云底座操作系统前端服务
  url: https://nestos.openeuler.org/
- service_alias: openEuler MirrorManager
  service_introduce: openEuler官网
  url: https://api.openeuler.org/mirrors/
- service_alias: openEuler Reproducible Builds
  service_introduce: openEuler可重复构建
  url: https://reproducible-builds.openeuler.org
- service_alias: Community Talent Certification
  service_introduce: openEuler社区人才认证IT系统
  url: https://talent-assessment.openeuler.org
- service_alias: Explainshell
  service_introduce: Shell命令解释服务
  url: https://explainshell.openeuler.sh
- service_alias: openEuler PlayGround2
  service_introduce: openEuler学习平台
  url: https://moocstudio.openeuler.org
- service_alias: Infra Ops
  service_introduce: 基础设施运维平台
  url: https://ops.osinfra.cn/
- service_alias: openEuler-ECS-Prometheus
  service_introduce: prometheus监控服务
  url: https://openeuler-ecs-beijing4-prometheus.osinfra.cn/graph
- service_alias: openGauss Usercenter
  service_introduce: openGauss社区用户中心
  url: https://id.opengauss.org/zh/profile
- service_alias: openGauss odd
  service_introduce: openGauss社区开发者大会人传人海报生成服务
  url: https://odd.opengauss.org
- service_alias: openGauss HongKong Website
  service_introduce: openGauss官网
  url: https://www.opengauss.org/zh/
- service_alias: openGauss Blog
  service_introduce: openGauss博客
  url: https://blog.opengauss.org
- service_alias: openGauss Meetings
  service_introduce: openGauss社区会议小程序
  url: https://opengauss.org/calendar/groups/
- service_alias: openGauss Moocstudio
  service_introduce: openGauss社区学习平台
  url: https://moocstudio.opengauss.org
- service_alias: openGauss Reproducible Builds
  service_introduce: openGauss可重复构建
  url: https://reproducible-builds.opengauss.org/
- service_alias: MindSpore Download
  service_introduce: MindSpore资源下载
  url: https://download.mindspore.cn/
- service_alias: MindSpore Binaries
  service_introduce: MindSpore包管理
  url: https://repo.mindspore.cn
- service_alias: voting
  service_introduce: helios投票服务
  url: https://helios-voting.osinfra.cn/
- service_alias: MindSpore WWW
  service_introduce: MindSpore官网
  url: https://www.mindspore.cn
- service_alias: MindSpore Xihe Doc
  service_introduce: N思文档
  url: https://xihe-docs.mindspore.cn/zh/introduction/
- service_alias: MindSpore Meetings
  service_introduce: MindSpore会议小程序
  url: https://api.mindspore.cn/meetings/sigs/
- service_alias: MindSpore Reproducible Builds
  service_introduce: MindSpore可重复构建
  url: https://reproducible-builds.mindspore.cn
- service_alias: openEuler Moscow
  service_introduce: openEuler俄语官网
  url: https://ru.openeuler.org/ru/
- service_alias: openEuler Beijing Mirror
  service_introduce: openEuler镜像北京下载地址
  url: http://121.36.97.194/
- service_alias: openEuler Document
  service_introduce: openEuler社区文档
  url: https://docs.openeuler.org/zh/
- service_alias: Etherpad
  service_introduce: 记事本
  url: https://etherpad.mindspore.cn
- service_alias: MindSpore Website
  service_introduce: MindSpore官网
  url: https://mindspore.cn
- service_alias: MindSpore Datastat
  service_introduce: MindSpore社区数据展示
  url: https://datastat.mindspore.cn
- service_alias: openEuler PlayGround
  service_introduce: openEuler学习平台
  url: https://moocstudio.openeuler.sh
- service_alias: Contributor License Agreement
  service_introduce: 开源社区SLA签署
  url: https://clasign.osinfra.cn/index
- service_alias: MindSpore paste
  service_introduce: 上传代码生成分享链接
  url: https://paste.mindspore.cn
- service_alias: openEuler paste
  service_introduce: 上传代码生成分享链接
  url: https://paste.openeuler.org
- service_alias: openGauss paste
  service_introduce: 上传代码生成分享链接
  url: https://paste.opengauss.org
- service_alias: openGauss Datastat
  service_introduce: openGauss社区数据展示
  url: https://datastat.opengauss.org
- service_alias: Majun anti-poison
  service_introduce: Majun防投毒
  url: https://anti-poison.osinfra.cn/checkRule/query/rules/config
- service_alias: Majun source clean
  service_introduce: Majun来源清洁
  url: https://source-clean.osinfra.cn
- service_alias: openEuler Copr
  service_introduce: openEuler用户仓服务
  url: https://eur.openeuler.openatom.cn/

